In [37]:
import torch
import h5py

In [2]:
a = torch.ones(3)

In [3]:
a

tensor([1., 1., 1.])

In [4]:
a[1]

tensor(1.)

In [5]:
float(a[1])

1.0

In [6]:
a[2]=2.0

In [7]:
a

tensor([1., 1., 2.])

In [16]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])

In [17]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [18]:
points.shape

torch.Size([6])

In [19]:
points[1:3]

tensor([1., 5.])

In [20]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [21]:
points.shape

torch.Size([3, 2])

In [23]:
points[0:2]

tensor([[4., 1.],
        [5., 3.]])

In [25]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
img_t

tensor([[[-1.6260, -0.8112, -1.4713, -0.4392,  1.3944],
         [ 0.0869,  0.3973, -0.7554, -0.1487, -0.4499],
         [ 0.1363, -0.5173, -0.0983, -1.2112, -0.0403],
         [ 0.0076,  0.3500,  0.9270, -0.4470, -1.4225],
         [ 0.9546,  0.2988,  0.9552, -0.2447, -1.4100]],

        [[ 0.2835, -1.0017,  1.0769, -0.3960, -1.5821],
         [ 0.3936, -0.8331,  0.4275,  0.2110, -1.2672],
         [-0.4397,  0.4887, -0.0961, -0.6080, -0.3668],
         [-1.4572,  0.1900,  0.7677, -0.4452,  0.2552],
         [ 2.3268,  0.0421, -0.1170, -0.4183, -0.2397]],

        [[-0.4649, -0.9379,  0.4724,  0.4037,  0.3833],
         [-0.3930,  1.1185, -0.1449, -0.1736,  1.3781],
         [ 0.6823, -2.2408,  2.0652,  0.6043,  2.1049],
         [-1.9045, -0.1765,  0.6765,  1.3261, -0.5666],
         [ 0.1334,  0.6474,  2.9471,  0.9148, -0.0198]]])

In [26]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])
weights

tensor([0.2126, 0.7152, 0.0722])

In [27]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
batch_t

tensor([[[[ 1.4927,  0.6267, -0.8048,  0.2668,  0.6162],
          [ 0.0511, -0.7939, -0.5364, -0.0377, -2.1114],
          [ 0.8283, -0.7240,  0.1345,  0.3923, -1.4078],
          [-0.5554, -0.5777,  0.6608, -0.6829, -1.2945],
          [ 1.5099,  1.3794, -0.0635,  2.1321, -0.0440]],

         [[ 1.4624, -0.4338,  0.6849,  1.1412, -0.6639],
          [-0.5926, -0.8329,  0.2038,  1.5060,  1.2354],
          [ 0.2541, -0.8218, -1.2446,  0.9568,  1.3206],
          [ 1.0611, -0.4364, -0.8134,  0.0626,  1.7453],
          [ 0.4007,  0.4026, -0.2598,  0.5635, -1.3857]],

         [[-1.1936, -1.3818, -0.8363, -2.7571,  0.1833],
          [ 0.8449,  0.8760,  0.4808,  0.1294,  0.0050],
          [-1.4462,  0.3434,  0.3079,  1.0333, -0.7990],
          [ 0.1569, -0.7500,  0.0380,  1.2541,  0.5152],
          [ 1.1163, -0.2241, -0.6303,  1.0146,  0.2070]]],


        [[[ 0.5019,  1.4974, -1.7626, -1.2754, -0.1974],
          [-1.8604,  0.7508, -0.3787, -0.7760, -0.5171],
          [-0.5149,  0.

In [28]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


/home/scott/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/tensor.py:605: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629427286/work/c10/core/TensorImpl.h:840.)
  return super(Tensor, self).refine_names(names)


In [31]:
img_named

tensor([[[-1.6260, -0.8112, -1.4713, -0.4392,  1.3944],
         [ 0.0869,  0.3973, -0.7554, -0.1487, -0.4499],
         [ 0.1363, -0.5173, -0.0983, -1.2112, -0.0403],
         [ 0.0076,  0.3500,  0.9270, -0.4470, -1.4225],
         [ 0.9546,  0.2988,  0.9552, -0.2447, -1.4100]],

        [[ 0.2835, -1.0017,  1.0769, -0.3960, -1.5821],
         [ 0.3936, -0.8331,  0.4275,  0.2110, -1.2672],
         [-0.4397,  0.4887, -0.0961, -0.6080, -0.3668],
         [-1.4572,  0.1900,  0.7677, -0.4452,  0.2552],
         [ 2.3268,  0.0421, -0.1170, -0.4183, -0.2397]],

        [[-0.4649, -0.9379,  0.4724,  0.4037,  0.3833],
         [-0.3930,  1.1185, -0.1449, -0.1736,  1.3781],
         [ 0.6823, -2.2408,  2.0652,  0.6043,  2.1049],
         [-1.9045, -0.1765,  0.6765,  1.3261, -0.5666],
         [ 0.1334,  0.6474,  2.9471,  0.9148, -0.0198]]],
       names=('channels', 'rows', 'columns'))

In [32]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [33]:
(
    points
    .t()
    .stride()
)

(1, 2)

In [34]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [35]:
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')